version: '3.9'
services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=fastapi_crud_demo
      - POSTGRES_PASSWORD=fastapi_crud_demo
      - POSTGRES_DB=fastapi_crud_demo
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  postgres_test:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=fastapi_crud_demo
      - POSTGRES_PASSWORD=fastapi_crud_demo
      - POSTGRES_DB=fastapi_crud_demo
      - DATABASE_URL=${DATABASE_URL_TEST}
    ports:
      - '5433:5432'
volumes:
  postgres:
    driver: local
